### ISSUE TITLE
useIsActive must be called from within CellProvider!

### ISSUE THREAD

**Issue by charlestbell** [fivecar/react-native-draglist#13]
Tried switching from draggable flatlist to this and I'm getting this error "useIsActive must be called from within CellProvider!" 

Do you know what might cause that?

**Comment by fivecar** [comment]
This project/codebase does not have `useIsActive` or `CellProvider` in it, so we'll likely need to see more code in order to speculate at what the error actually involves.

Are you potentially using the [useIsActive hook](https://ui-router.github.io/react/docs/latest/modules/_hooks_useisactive_.html#useisactive) from @ui-router/react? That's where I see a reference to `useIsActive`.

If it's still not clear what's going on, please feel free to post more code/context. Since this project doesn't use either of those components, it's almost definitely not related to this project, but I'm happy to help if I can.

**Comment by charlestbell** [comment]
Gotcha. I'll try in a fresh project and build up from there.

**Comment by charlestbell** [comment]
Turns out I left the <ScaleDecorator></ScaleDecorator> in my code. That's what was throwing the error because it was no longer inside a DraggableFlatlist. You can close this issue.

**Comment by charlestbell** [comment]
BTW, this library solved my issue of being unable to drag on Android. Excellent work! ⭐

**Comment by fivecar** [comment]
Awesome. Thanks for following up, @charlestbell . I'm glad it's resolved — and it's great to hear the library's working out for you!
