### ISSUE TITLE
After adding CellRendererComponent, onDragStart and onDragEnd works but onReordered does not perform

### ISSUE THREAD

**Issue by sandeepa91** [fivecar/react-native-draglist#22]
After adding **CellRendererComponent**, onDragStart and onDragEnd works but onReordered does not perform

Here Is the my Code 

```
<DragList
        data={dataTalentPoolGroup}
        keyExtractor={keyExtractor}
        onReordered={onReordered}
        renderItem={renderItem}
        CellRendererComponent={({ children, index, style, ...props }) => {
          const cellStyle = [
            style,
            { zIndex: dataTalentPoolGroup.length - index }
          ]
          return (
            <View style={cellStyle} index={index} {...props}>
              {children}
            </View>
          )
        }}
      />
```

But DragList not works after adding the **CellRendererComponent**

```
CellRendererComponent={({ children, index, style, ...props }) => {
          const cellStyle = [
            style,
            { zIndex: dataTalentPoolGroup.length - index }
          ]

          return (
            <View style={cellStyle} index={index} {...props}>
              {children}
            </View>
          )
        }}
```

Can Some one helps me to fix this? Thank You!

**Comment by fivecar** [comment]
@sandeepa91 : thanks for reporting this. Right now, the library doesn't support supplying your own CellRendererComponent (and neither does react-native-draggable-flatlist, IIUC). Is what you'd like to do not doable through providing just a `renderItem`?

I think it'd be hard to add `CellRendererComponent` override support holistically, in that react-native-draglist provides its own version of that in order to control how it enables draggability and what not.
