### ISSUE TITLE
Dragging doesn't work with New Architecture (0.76)

### ISSUE THREAD

**Issue by hollanderbart** [fivecar/react-native-draglist#53]
Thanks for maintaining this library. After upgrading to the latest React Native version 0.76.3, the dragging behaviour is not working. The item doesn't move vertically. 

Can you please have a look at what could be the solution?

Thanks!

repo: https://github.com/hollanderbart/RN-BusinessCards

https://github.com/user-attachments/assets/1d92ac52-103a-46e2-a9c0-e4bc00b6aae1

@fivecar can you please review the issue?

**Comment by fivecar** [comment]
Thanks for taking the time to report this, @hollanderbart . Super unclear what the problem was. Empirically derived the solution, which you can see in `index.tsx` in https://github.com/fivecar/react-native-draglist/pull/54 (ignore all the other changes in that PR, which upgraded the example project to RN 0.76.3).

Searching the internet didn't yield a reason for this breakage either. But I've now gotten things working.

**Comment by fivecar** [comment]
Release 3.6.3 just done, based on this issue. Thanks again, @hollanderbart , for taking the time to make this project better. https://github.com/fivecar/react-native-draglist/releases/tag/3.6.3

**Comment by hollanderbart** [comment]
We use the project in our app, so we had to have a fix for this issue 😉
I like the philosophy of this solution and also made a blogpost about it: https://xebia.com/blog/drag-drop-sort-implementing-draggable-sorting-in-react-native/

That's for your quick response and fix 🎉

**Comment by fivecar** [comment]
@hollanderbart : thank you! Just linked to your article via https://github.com/fivecar/react-native-draglist/pull/56 in the project's README.md.
